name: CD

on:
  push:
    branches:
      - main

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKERHUB_KEY: ${{ secrets.DOCKER_KEY }}
  IMAGE_NAME: myapp

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_KEY }}

      - name: Build Docker image
        run: docker build -t ahsisti/${{ env.IMAGE_NAME }}:${GITHUB_SHA::7} .

      - name: Push Docker image
        run: docker push ahsisti/${{ env.IMAGE_NAME }}:${GITHUB_SHA::7}

      - name: Update myapp-deployment.yml
        run: |
          cd k8s
          sed -i 's|image: ahsisti/myapp:.*|image: ahsisti/myapp:'${GITHUB_SHA::7}'|' myapp-deployment.yml 
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add myapp-deployment.yml
          git commit -m "Update myapp-deployment.yml"
          git push
